Repository GDSC-CAU/Thanks-Clip, pull requests merged in 2023-01, with the labels that each got.

#1 Merge feature/1lsang/routing structure
  .eslintrc.json
  .lintstagedrc
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/common/Header.jsx
  src/components/common/Layout.jsx
  src/components/common/ProgressBar.jsx
  src/components/common/README.md
  src/components/common/index.js
  src/components/pages/README.md
  src/main.jsx
  src/pages/README.md
  src/pages/error/index.jsx
  src/pages/home/index.jsx
  src/pages/index.js
  src/pages/step1/index.jsx
  src/pages/step2/index.jsx
  src/pages/step3/index.jsx
  src/pages/step4/index.jsx
  src/router/LinkTo.jsx
  src/router/README.md
  src/router/RouterProvider.jsx
  src/router/config.jsx
  src/router/index.js
Labels: 기능추가

#2 feat: add Title common component
  src/components/common/Title.jsx
  src/components/common/index.js
Labels: 기능추가

#4 feat: add ProgressBar common component
  src/components/common/Layout.jsx
  src/components/common/ProgressBar.jsx
Labels: 기능추가

#5 feat : add pageButton(prev,next) common compoent
  package.json
  pnpm-lock.yaml
  src/components/common/Button.jsx
  src/components/common/PrevButton.jsx
  src/components/common/index.js
Labels: 기능추가

#7 Refactor/danpacho/common layout
  src/components/common/Layout.jsx
  src/components/common/PrevButton.jsx
  src/components/common/ProgressBar.jsx
Labels: 리팩토링

#6 Feature/danpacho/modal
  src/components/common/Modal.jsx
  src/components/common/index.js
  src/pages/step1/index.jsx
  tailwind.config.cjs
Labels: 기능추가

#8 feat: add step2 page(keyword selection) view
  src/components/common/Button.jsx
  src/components/pages/index.js
  src/components/pages/step2/KeywordButton.jsx
  src/components/pages/step2/KeywordTextList.json
  src/pages/step2/index.jsx
Labels: 기능추가

#10 feat: add `editor-layout` components
  app/step/2/page.js
  app/step/3/components/Container.jsx
  app/step/3/components/EditorToolBar.jsx
  app/step/3/components/EditorToolBarSelector.jsx
  app/step/3/components/LetterEditorLayout.jsx
  app/step/3/page.js
  app/step/layout.js
Labels: 기능추가

#11 Feature/danpacho/letter component
  app/step/3/components/Letter/Canvas.jsx
  app/step/3/components/Letter/Editor/ToolBar.jsx
  app/step/3/components/Letter/Editor/ToolBarSelector.jsx
  app/step/3/components/Letter/Editor/index.js
  app/step/3/components/Letter/index.jsx
  app/step/3/components/LetterEditorLayout.jsx
  app/step/3/components/Test.jsx
  app/step/3/components/common/Container.jsx
  app/step/3/page.js
Labels: 기능추가

#13 Feature/danpacho/component to svg string
  app/SvgTest.jsx
  app/page.js
  next.config.js
  package.json
  pages/api/rendering.js
  pages/api/svg.js
  pnpm-lock.yaml
Labels: 기능추가

#14 Feature/1lsang/letter shape
  app/step/3/components/Letter/Canvas.jsx
  app/step/3/components/Letter/LetterShape.jsx
  app/step/3/components/Letter/index.jsx
Labels: 기능추가

#15 Feature/koeunseooooo/letter text component
  app/step/3/components/Letter/Editor/FontToolBar.jsx
  app/step/3/components/Letter/Editor/ToolBar.jsx
  app/step/3/components/Letter/LetterShape.jsx
  app/step/3/components/Letter/LetterText.jsx
  app/step/3/components/Letter/index.jsx
  atoms/letter.js
  next.config.js
  package.json
  pnpm-lock.yaml
Labels: 기능추가

#18 Feature/danpacho/sticker
  app/step/3/components/Letter/Editor/Stickers/Sticker/Circle.jsx
  app/step/3/components/Letter/Editor/Stickers/Sticker/Heart.jsx
  app/step/3/components/Letter/Editor/Stickers/Sticker/Star.jsx
  app/step/3/components/Letter/Editor/Stickers/Sticker/index.jsx
  app/step/3/components/Letter/Editor/Stickers/StickerEditor.jsx
  app/step/3/components/Letter/Editor/Stickers/StickerManager.jsx
  app/step/3/components/Letter/Editor/Stickers/useStickerManager.js
  app/step/3/components/Letter/Editor/ToolBar.jsx
  app/step/3/components/Letter/Editor/ToolBarSelector.jsx
  app/step/3/components/Letter/LetterShape.jsx
  app/step/3/components/Letter/index.jsx
  app/step/layout.js
  atoms/index.js
  atoms/letter.js
  atoms/sticker.js
Labels: 기능추가

#19 Feature/1lsang/background color component
  app/step/3/components/Letter/Editor/ColorToolBar.jsx
  app/step/3/components/Letter/Editor/ToolBar.jsx
  app/step/3/components/Letter/LetterShape.jsx
Labels: 기능추가

#20 Feature/1lsang/remotion video
  video/Composition.jsx
  video/Root.jsx
  video/components/Envelope.jsx
  video/components/Keywords.jsx
  video/components/LogoSM.jsx
  video/components/PaperPlane.jsx
  video/components/To.jsx
Labels: 기능추가

#21 Feature/danapcho/letter type tool bar
  app/step/3/components/Letter/Editor/ShapeToolBar/Icon/Hole.jsx
  app/step/3/components/Letter/Editor/ShapeToolBar/Icon/Overlap.jsx
  app/step/3/components/Letter/Editor/ShapeToolBar/Icon/Torn.jsx
  app/step/3/components/Letter/Editor/ShapeToolBar/index.jsx
  app/step/3/components/Letter/Editor/ToolBar.jsx
Labels: 기능추가

#24 Feature/danpacho/refactor
  app/SvgTest.jsx
  app/head.js
  app/step/3/components/Letter/Editor/ToolBarSelector.jsx
  app/step/4/components/Download.jsx
  app/step/RenderOnMount.jsx
  app/step/layout.js
  app/step/page.js
  pages/api/rendering.js
  pages/api/svg.js
  video/Composition.jsx
  video/components/PaperPlane.jsx
Labels: 기능추가, 리팩토링

#23 Feature/koeunseooooo/kakao share
  app/download/page.js
  app/step/4/components/KakaoShareLink.jsx
  app/step/4/page.js
  package.json
  pnpm-lock.yaml
Labels: 기능추가

#25 feat: add `LetterButton``LetterToName` to step4
  app/step/4/components/LetterButton.jsx
  app/step/4/components/LetterToName.jsx
  app/step/4/page.js
Labels: 기능추가

#26 Feature/danpacho/step3 preview
  app/common/Modal.jsx
  app/step/3/components/Letter/LetterStatic.jsx
  app/step/3/components/Preview/index.jsx
  app/step/3/page.js
  app/step/4/page.js
Labels: 기능추가

#27 Feature/danpacho/aws video rendering
  app/SvgTest.jsx
  app/download/page.js
  app/step/3/components/PreviewLetter/index.jsx
  app/step/3/components/Test.jsx
  app/step/3/page.js
  app/step/4/components/ClipPreview.jsx
  app/step/4/components/Download.jsx
  app/step/4/components/LetterButton.jsx
  app/step/4/page.js
  constant/cookie.js
  constant/deployConfig.js
  constant/path.js
  pages/api/rendering.js
  pages/api/svg.js
  pnpm-lock.yaml
  scripts/deploy.js
  video/Composition.jsx
  video/Root.jsx
  video/components/Letter.jsx
Labels: 기능추가

#29 Feature/koeunseooooo/loading
  app/step/4/airplane.module.css
  app/step/4/loading.js
  package.json
  pnpm-lock.yaml
Labels: 기능추가

#30 fix: remove "select-none" in step1 textarea
  app/step/1/components/Textarea.jsx
Labels: 리팩토링

#32 Refactor/danpacho/final deploy refactor
  app/step/4/components/KakaoShareLink.jsx
  pages/api/rendering.js
  video/components/Letter.jsx
Labels: 리팩토링

#31 Feature/1lsang/layout fix
  app/page.js
  app/step/1/components/LetterForm.jsx
  app/step/2/components/KeywordButton.jsx
  app/step/2/components/KeywordForm.jsx
  app/step/3/components/Letter/LetterShape.jsx
  app/step/3/page.js
  app/step/4/components/LetterButton.jsx
  app/step/4/page.js
  app/step/RenderOnMount.jsx
  video/components/Letter.jsx
Labels: 기능추가

#28 Feature/likeyeon/download page
  app/download/components/Confetti.jsx
  app/download/components/DownloadTitle.jsx
  app/download/components/Envelope.jsx
  app/download/components/download.module.css
  app/download/page.js
  app/step/4/components/LetterButton.jsx
  atoms/sticker.js
  package.json
  pnpm-lock.yaml
Labels: 기능추가

#34 Fix/1lsang/layout
  app/common/Button.jsx
  app/layout.js
  app/page.js
  app/step/1/components/LetterForm.jsx
  app/step/1/components/Textarea.jsx
  app/step/2/components/KeywordForm.jsx
  app/step/2/components/KeywordTextList.js
  app/step/3/components/Letter/Editor/ShapeToolBar/index.jsx
  app/step/3/components/Letter/Editor/Stickers/StickerManager.jsx
  app/step/3/components/Letter/Editor/Stickers/StickerToolBar.jsx
  app/step/3/components/Letter/Editor/Stickers/useStickerManager.js
  app/step/3/components/Letter/Editor/ToolBar.jsx
  app/step/3/components/Letter/Editor/ToolBarSelector.jsx
  app/step/3/components/Letter/LetterText.jsx
  app/step/3/components/Letter/index.jsx
  app/step/3/page.js
  app/step/4/components/ClipPreview.jsx
  app/step/4/components/KakaoShareLink.jsx
  app/step/4/components/LetterButton.jsx
  app/step/4/components/LetterToName.jsx
  app/step/4/page.js
  app/step/RenderOnMount.jsx
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  tailwind.config.cjs
Labels: 기능강화

#35 Fix replace satori with @vercel/og
  .env.example
  app/head.js
  app/index.css
  app/step/4/cache.js
  app/step/4/components/ClipPreview.jsx
  app/step/4/components/Download.jsx
  app/step/4/components/Viewer.jsx
  app/step/4/page.js
  constant/path.js
  package.json
  pages/api/_aws/index.js
  pages/api/image.jsx
  pages/api/rendering.js
  pages/api/svg.js
  pnpm-lock.yaml
  scripts/deploy.js
  scripts/destroy.js
  scripts/increase.js
  vercel.json
  video/CompositionServer.jsx
  video/components/Letter.jsx
Labels: 버그, 리팩토링

#38 Fix/danpacho/kakao share download
  app/download/page.js
  app/step/4/components/KakaoShareLink.jsx
  app/step/4/components/LetterButton.jsx
  app/step/4/page.js
Labels: 버그, 리팩토링

#39 Feature/danpacho/download status
  app/download/components/Download.jsx
  app/download/components/DownloadClient.jsx
  app/download/page.js
  app/step/4/components/KakaoShareLink.jsx
  pages/api/rendering.js
Labels: 버그, 기능추가
